### ISSUE TITLE
not compatible with the chatbot plugin v1.2.22

### ISSUE THREAD

**Issue by jjbully** [WeChatAI/openai-plugin-overwrite#6]
```
WAService.js:1 thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'match' of undefined 
 TypeError: Cannot read property 'match' of undefined
    at o (WAService.js:1:1324940)
    at mt (WAService.js:1:1418173)
    at Rt.r.Page (WAService.js:1:1433143)
    at http://127.0.0.1:13736/appservice/__onlineplugin__/wx8c631f7e9f2465e1/1.2.22/appservice.js:2593:14
    at h (WAService.js:1:1439877)
    at WAService.js:1:1439370
    at http://127.0.0.1:13736/appservice/__onlineplugin__/wx8c631f7e9f2465e1/1.2.22/appservice.js:2594:10
    at f (WAService.js:1:1439316)
    at t.requirePlugin (WAService.js:1:1440600)
    at http://127.0.0.1:13736/appservice/__onlineplugin__/wx8c631f7e9f2465e1/1.2.22/appservice.js:2657:2(env: macOS,mp,1.05.2106300; lib: 2.8.3)
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
c @ VM9 asdebug.js:1
r @ VM9 asdebug.js:1
window.onerror @ VM494:1
error (async)
t.default @ VM494:1
137 @ VM494:1
n @ VM494:1
(anonymous) @ VM494:1
(anonymous) @ VM494:1
VM539:5 app.js错误:
 TypeError: Cannot read property 'match' of undefined
    at o (WAService.js:1)
    at mt (WAService.js:1)
    at Rt.r.Page (WAService.js:1)
    at VM536 appservice.js:2593
    at h (WAService.js:1)
    at WAService.js:1
    at VM536 appservice.js:2594
    at f (WAService.js:1)
    at t.requirePlugin (WAService.js:1)
    at app.js? [sm]:2(env: macOS,mp,1.05.2106300; lib: 2.8.3)
(anonymous) @ VM539:5
doWhenAllScriptLoaded @ VM518:1615
scriptLoaded @ VM518:1643
(anonymous) @ VM518:1668
Promise.then (async)
(anonymous) @ VM518:1689
(anonymous) @ VM518:1693
loadScripts @ assubloader.js:1
async function (async)
loadScripts @ assubloader.js:1
loadAppResourceScripts @ assubloader.js:1
(anonymous) @ VM513:1
t.loadScripts @ VM9 asdebug.js:1
loadAppService @ VM9 asdebug.js:1
messagerCallback @ VM9 asdebug.js:1
(anonymous) @ VM9 asdebug.js:1
f @ VM9 asdebug.js:1
g @ VM9 asdebug.js:1
(anonymous) @ VM9 asdebug.js:1
_ws.onmessage @ VM9 asdebug.js:1
WAService.js:1 thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'match' of undefined 
 TypeError: Cannot read property 'match' of undefined
    at o (WAService.js:1:1324940)
    at mt (WAService.js:1:1418173)
    at Rt.r.Page (WAService.js:1:1433143)
    at http://127.0.0.1:13736/appservice/__onlineplugin__/wx8c631f7e9f2465e1/1.2.22/appservice.js:2593:14
    at h (WAService.js:1:1439877)
    at WAService.js:1:1439370
    at http://127.0.0.1:13736/appservice/__onlineplugin__/wx8c631f7e9f2465e1/1.2.22/appservice.js:2594:10
    at f (WAService.js:1:1439316)
    at t.requirePlugin (WAService.js:1:1440600)
    at http://127.0.0.1:13736/appservice/app.js:5:14(env: macOS,mp,1.05.2106300; lib: 2.8.3)
```

**Comment by jjbully** [comment]
it solved by change the code to ` "libVersion": "2.18.0",` in project.config.json, however, there is unhandled promise rejection, think which is bug of the plugin Openai Widget
